# Generated by Django 5.2.8 on 2025-12-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_appointment_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rescheduled',
            field=models.BooleanField(default=False),
        ),
    ]
