# Generated by Django 5.2.8 on 2025-11-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('service', models.CharField(choices=[('barba', 'Fazer a barba'), ('cabelo', 'Cortar o cabelo'), ('combo', 'Barba + cabelo')], max_length=10)),
                ('barber', models.CharField(choices=[('Japa', 'Japa')], max_length=10)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('payment_status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('falhou', 'Falhou')], default='pendente', max_length=10)),
            ],
            options={
                'unique_together': {('barber', 'date', 'hour')},
            },
        ),
    ]
