# Generated by Django 5.2.8 on 2025-11-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_phone',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
