# Generated by Django 6.0 on 2025-12-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_appointment_rescheduled'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='agendamento_appointment',
        ),
    ]
