# Generated by Django 6.0 on 2025-12-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0006_appointment_cancel_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('barber', 'Barbeiro'), ('client', 'Cliente'), ('system', 'Sistema')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('cancelado', 'Cancelado')], default='ativo', max_length=10),
        ),
    ]
