# Generated by Django 6.0 on 2025-12-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0007_alter_appointment_cancelled_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ativo')), fields=('barber', 'date', 'hour'), name='unique_active_appointment'),
        ),
    ]
