# Generated by Django 6.0 on 2025-12-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='user',
            name='card_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterModelTable(
            name='user',
            table='tb_usuarios',
        ),
    ]
