# Generated by Django 5.2.9 on 2025-12-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_card_id_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_name',
            field=models.CharField(default='theme-green', max_length=32),
        ),
    ]
