from .appointment import (
    BARBER_CHOICES,
    CANCELLED_BY_CHOICES,
    PAYMENT_CHOICES,
    PAYMENT_METHOD_CHOICES,
    SERVICE_CHOICES,
    STATUS_CHOICES,
)

__all__ = [
    'BARBER_CHOICES',
    'CANCELLED_BY_CHOICES',
    'PAYMENT_CHOICES',
    'PAYMENT_METHOD_CHOICES',
    'SERVICE_CHOICES',
    'STATUS_CHOICES',
]
